### ISSUE TITLE
Build wheel: finished with status 'error'

### ISSUE THREAD

**Issue by Ap0ph1s-W4ite** [maxime1992/linak-2-mqtt#11]
When I try to run the command `docker build -t linak-2-mqtt .` I am receiving the following wheel error.

```
pi@FermPi:~/linak-2-mqtt $ sudo docker build -t linak-2-mqtt .
Sending build context to Docker daemon  318.5kB
Step 1/18 : FROM ubuntu:focal
 ---> 0a13b0a84dab
Step 2/18 : RUN apt update -y && apt upgrade -y
 ---> Using cache
 ---> 4d0bee4cffbe
Step 3/18 : RUN apt install python3 python3-pip -y
 ---> Using cache
 ---> 1917ffb165c4
Step 4/18 : ENV TZ=Europe/Paris
 ---> Using cache
 ---> 656329445726
Step 5/18 : RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
 ---> Using cache
 ---> d08d4c6d42ff
Step 6/18 : RUN apt install bluez -y
 ---> Using cache
 ---> 5800ee81ffa9
Step 7/18 : RUN apt install build-essential libglib2.0-dev libical-dev libreadline-dev libudev-dev libdbus-1-dev libdbus-glib-1-dev bluetooth libbluetooth-dev usbutils -y
 ---> Using cache
 ---> cdd90dea4bee
Step 8/18 : RUN pip3 install idasen-controller==2.0.1
 ---> Running in 16d47c4e0efd
Collecting idasen-controller==2.0.1
  Downloading idasen_controller-2.0.1-py3-none-any.whl (10 kB)
Collecting PyYAML<=6.0.0,>=5.4.1
  Downloading PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpjprtw9xp get_requires_for_build_wheel /tmp/tmpnfgp2v_i
       cwd: /tmp/pip-install-n9vxfd6_/PyYAML
  Complete output (48 lines):
  running egg_info
  writing lib/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/tmp/tmpjprtw9xp", line 280, in <module>
      main()
    File "/tmp/tmpjprtw9xp", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpjprtw9xp", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 288, in <module>
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 321, in run
      self.find_sources()
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
      mm.run()
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 550, in run
      self.add_defaults()
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
      super().add_defaults()
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "<string>", line 204, in get_source_files
    File "/tmp/pip-build-env-5qjwrx6j/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpjprtw9xp get_requires_for_build_wheel /tmp/tmpnfgp2v_i Check the logs for full command output.
The command '/bin/sh -c pip3 install idasen-controller==2.0.1' returned a non-zero code: 1
```

**Comment by maxime1992** [comment]
Hi! I'm afraid I'm not using this at the moment as my desk is too far from my server now.

If you manage to debug it feel free to raise a pull request :pray:

**Comment by Ap0ph1s-W4ite** [comment]
Hi,

I'm back with some fixes. I created a pull request with all the fixes that I found during my setup. #12
